/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DonateRouteImport } from './routes/donate'
import { Route as HomeRouteImport } from './routes/home'
import { Route as TheCarRouteImport } from './routes/the-car'

const DonateRoute = DonateRouteImport.update({
  id: '/donate',
  path: '/donate',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const TheCarRoute = TheCarRouteImport.update({
  id: '/the-car',
  path: '/the-car',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/donate': typeof DonateRoute
  '/home': typeof HomeRoute
  '/the-car': typeof TheCarRoute
}
export interface FileRoutesByTo {
  '/donate': typeof DonateRoute
  '/home': typeof HomeRoute
  '/the-car': typeof TheCarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/donate': typeof DonateRoute
  '/home': typeof HomeRoute
  '/the-car': typeof TheCarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/donate' | '/home' | '/the-car'
  fileRoutesByTo: FileRoutesByTo
  to: '/donate' | '/home' | '/the-car'
  id: '__root__' | '/donate' | '/home' | '/the-car'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DonateRoute: typeof DonateRoute
  HomeRoute: typeof HomeRoute
  TheCarRoute: typeof TheCarRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/donate': {
      id: '/donate'
      path: '/donate'
      fullPath: '/donate'
      preLoaderRoute: typeof DonateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/the-car': {
      id: '/the-car'
      path: '/the-car'
      fullPath: '/the-car'
      preLoaderRoute: typeof TheCarRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  DonateRoute: DonateRoute,
  HomeRoute: HomeRoute,
  TheCarRoute: TheCarRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
